name: flutter_streaming_audio_video_100ms
description: A Flutter package for streaming audio and video with a 100ms delay.
version: 0.0.1
homepage: https://github.com/jmrashed/flutter_streaming_audio_video_100ms
repository: https://github.com/jmrashed/flutter_streaming_audio_video_100ms.git

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0
  video_player: ^2.2.0
  flutter_audio_recorder: 0.5.5
  permission_handler: ^10.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
